# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ToolVersion'),
        ),
    ]
