# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyinstance',
            name='public',
        ),
        migrations.AlterField(
            model_name='galaxyinstance',
            name='url',
            field=models.URLField(help_text='Instance URL', null=True),
        ),
    ]
