# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyinstance',
            name='dnsdomainname',
        ),
        migrations.AddField(
            model_name='galaxyinstance',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
