# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyinstance',
            name='norm_users_recent',
        ),
        migrations.AddField(
            model_name='galaxyinstance',
            name='last_import',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='external_job_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('instance', 'external_job_id')]),
        ),
    ]
