# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyinstance',
            name='jobs_total',
            field=models.IntegerField(default=0),
        ),
    ]
