# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170721_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyinstance',
            name='publicly_visible',
        ),
    ]
