# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 17:42
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160810_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolversion',
            options={'ordering': ('-version',)},
        ),
        migrations.AlterField(
            model_name='galaxyinstance',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='api._Tagulous_GalaxyInstance_tags'),
        ),
    ]
