# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160603_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxyinstance',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tool'),
        ),
    ]
