# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160603_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='metrics_cpuinfo_cores_allocated',
            new_name='metrics_core_galaxy_slots',
        ),
        migrations.AlterField(
            model_name='galaxyinstance',
            name='jobs_run',
            field=models.ManyToManyField(blank=True, related_name='job_recent_data', to='api.IntegerDataPoint'),
        ),
        migrations.AlterField(
            model_name='galaxyinstance',
            name='users_recent',
            field=models.ManyToManyField(blank=True, related_name='user_recent_data', to='api.IntegerDataPoint'),
        ),
        migrations.AlterField(
            model_name='galaxyinstance',
            name='users_total',
            field=models.ManyToManyField(blank=True, related_name='user_total_data', to='api.IntegerDataPoint'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('instance', 'tool', 'date')]),
        ),
    ]
