# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160625_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([]),
        ),
    ]
