# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160603_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tool_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tool_version',
        ),
        migrations.AddField(
            model_name='job',
            name='tool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Tool'),
            preserve_default=False,
        ),
    ]
