# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparam',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
