# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160603_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
    ]
