# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160810_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyinstance',
            name='norm_users_recent',
            field=models.IntegerField(default=0),
        ),
    ]
