# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180618_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricnumeric',
            name='value',
            field=models.DecimalField(decimal_places=7, max_digits=26),
        ),
    ]
