# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180618_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='extension',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='param_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tool_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tool_version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobparam',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metricnumeric',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='metricnumeric',
            name='plugin',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='metrictext',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='metrictext',
            name='plugin',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='metrictext',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
