# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-31 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaxyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Publicly accesible instance URL', null=True)),
                ('title', models.CharField(help_text='The name / title of the instance. E.g. GalaxyP', max_length=256, null=True)),
                ('description', models.TextField(help_text='Any extra description you wish to add.', null=True)),
                ('public', models.BooleanField(default=False, help_text='Is the instance open to the public?')),
                ('users_recent', models.TextField(blank=True)),
                ('users_total', models.TextField(blank=True)),
                ('jobs_run', models.TextField(blank=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_import', models.IntegerField(default=-1)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('external_job_id', models.IntegerField(default=-1)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GalaxyInstance')),
            ],
        ),
        migrations.CreateModel(
            name='JobParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, 'int'), (1, 'float'), (2, 'text')])),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=128)),
                ('tool_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tool')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='metrics',
            field=models.ManyToManyField(to='api.Metric'),
        ),
        migrations.AddField(
            model_name='job',
            name='params',
            field=models.ManyToManyField(to='api.JobParam'),
        ),
        migrations.AddField(
            model_name='job',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ToolVersion'),
        ),
        migrations.AddField(
            model_name='galaxyinstance',
            name='tools',
            field=models.ManyToManyField(blank=True, to='api.ToolVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('instance', 'external_job_id')]),
        ),
    ]
