# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxyinstance',
            name='last_import',
            field=models.FloatField(default=-1),
        ),
    ]
